### ISSUE TITLE
run_factory crashes with new databases

### ISSUE THREAD

**Issue by BatedUrGonnaDie** [glacials/splits-io#155]
Postgres will throw a table not found, which blocks creation of the database and tables.

**Comment by glacials** [comment]
What command are you running when you get the error?

Try a `rake db:migrate` first, your schema may be outdated.

**Comment by BatedUrGonnaDie** [comment]
Tried that, tried, `rake db:setup` and `rake db:schema:load` as well.  All fail with the same error.

**Comment by BatedUrGonnaDie** [comment]
I should note that when I ran these 3 commands is when the error was thrown.  Sorry if I didn't specify that before.

**Comment by glacials** [comment]
Ok, how about a

```bash
rake db:drop db:create db:migrate
```

(this will delete the db and all data in it, then recreate)

If this doesn't work, can you paste the entire error you get here?

**Comment by BatedUrGonnaDie** [comment]
Here you go
```
PG::UndefinedTable: ERROR:  relation "run_files" does not exist
LINE 5:                WHERE a.attrelid = '"run_files"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"run_files"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum

rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "run_files" does not exist
LINE 5:                WHERE a.attrelid = '"run_files"'::regclass
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"run_files"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/attributes.rb:91:in `columns'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/attributes.rb:96:in `columns_hash'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:968:in `block in create_binds'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:965:in `each'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:965:in `partition'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:965:in `create_binds'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.2/relation_extensions.rb:116:in `expand_attrs_from_hash'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/relation_extensions.rb:195:in `block in build_where'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/relation_extensions.rb:190:in `map'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/relation_extensions.rb:190:in `build_where'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:584:in `where!'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:574:in `where'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/relation_extensions.rb:36:in `where'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/querying.rb:10:in `where'
/media/sf_github/splits-io/app/models/run_file.rb:13:in `for_text'
/media/sf_github/splits-io/app/models/run_file.rb:8:in `for_file'
/media/sf_github/splits-io/spec/factories/run_factory.rb:3:in `block (2 levels) in <top (required)>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:18:in `factory'
/media/sf_github/splits-io/spec/factories/run_factory.rb:2:in `block in <top (required)>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:49:in `run'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:7:in `define'
/media/sf_github/splits-io/spec/factories/run_factory.rb:1:in `<top (required)>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:19:in `each'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:15:in `each'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl_rails-4.4.1/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/media/sf_github/splits-io/config/environment.rb:5:in `<top (required)>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/home/alex/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/alex/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
PG::UndefinedTable: ERROR:  relation "run_files" does not exist
LINE 5:                WHERE a.attrelid = '"run_files"'::regclass
                                          ^
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `block in log'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:460:in `log'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/attributes.rb:91:in `columns'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/attributes.rb:96:in `columns_hash'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:968:in `block in create_binds'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:965:in `each'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:965:in `partition'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:965:in `create_binds'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.2/relation_extensions.rb:116:in `expand_attrs_from_hash'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/relation_extensions.rb:195:in `block in build_where'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/relation_extensions.rb:190:in `map'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/relation_extensions.rb:190:in `build_where'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:584:in `where!'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/relation/query_methods.rb:574:in `where'
/home/alex/.rvm/gems/ruby-2.1.5/gems/squeel-1.2.3/lib/squeel/adapters/active_record/4.1/relation_extensions.rb:36:in `where'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activerecord-4.2.0/lib/active_record/querying.rb:10:in `where'
/media/sf_github/splits-io/app/models/run_file.rb:13:in `for_text'
/media/sf_github/splits-io/app/models/run_file.rb:8:in `for_file'
/media/sf_github/splits-io/spec/factories/run_factory.rb:3:in `block (2 levels) in <top (required)>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:18:in `instance_eval'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:18:in `factory'
/media/sf_github/splits-io/spec/factories/run_factory.rb:2:in `block in <top (required)>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:49:in `instance_eval'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:49:in `run'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/syntax/default.rb:7:in `define'
/media/sf_github/splits-io/spec/factories/run_factory.rb:1:in `<top (required)>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:20:in `block (2 levels) in find_definitions'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:19:in `each'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:19:in `block in find_definitions'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:15:in `each'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl-4.4.0/lib/factory_girl/find_definitions.rb:15:in `find_definitions'
/home/alex/.rvm/gems/ruby-2.1.5/gems/factory_girl_rails-4.4.1/lib/factory_girl_rails/railtie.rb:21:in `block in <class:Railtie>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `call'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/media/sf_github/splits-io/config/environment.rb:5:in `<top (required)>'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/alex/.rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/home/alex/.rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/home/alex/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/home/alex/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```

**Comment by glacials** [comment]
Tests have been brokenish since updating to Rails 5, and I'm not sure now if that's related, but I believe this was being caused by FactoryGirl being loaded on any `rails` command, which it shouldn't be. Let me know if the above commit fixes your problem (still couldn't reproduce).

**Comment by BatedUrGonnaDie** [comment]
Yep, looks like everything is working fine now.
