### ISSUE TITLE
Trouble running development environment with Docker Toolbox

### ISSUE THREAD

**Issue by jhobz** [glacials/splits-io#330]
Splitting discussion from #322 out into its own issue as per the request in the README.

I'm trying to use [Docker Toolbox](https://docs.docker.com/toolbox/overview/) to run the app locally since newer versions of Docker require Windows Pro/Enterprise. As the top of the link states, this is a legacy version of Docker, so the answer may just be "sorry, it's not gonna work," but I figured I'd at least give it a shot.

When trying to run `docker-compose up`, I'm greeted with the following output:
```bash
$ docker-compose up
Starting splitsio_s3_1 ...
Starting splitsio_db_1 ...
Starting splitsio_s3_1
Starting splitsio_s3_1 ... done
Starting splitsio_web_1 ...
Starting splitsio_web_1 ... done
Attaching to splitsio_db_1, splitsio_s3_1, splitsio_web_1
db_1   | 2017-10-19 10:02:45.165 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2017-10-19 10:02:45.165 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2017-10-19 10:02:45.167 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
s3_1   | [2017-10-19 10:02:45] INFO  WEBrick 1.3.1
db_1   | 2017-10-19 10:02:45.190 UTC [19] LOG:  database system was shut down at 2017-10-19 10:02:37 UTC
```

It seems like everything is mostly ok, but when I try to go to `localhost:3000` in the browser, nothing is found. I tried `localhost:5432` as well due to the output and still get nothing.

If it's simply a matter of syntax or something between the two Docker versions, I wonder if we can update the README to include both for those who use one or the other.

**Comment by glacials** [comment]
`localhost:3000` is definitely correct, `5432` is the database port (see the first two characters of the line -- we're looking for output from `web_1`, the Rails container).

How long did you wait after the logs settled before trying to access it in a browser? I notice that sometimes the site isn't accessible for a good 10s or so after the log stops printing startup info.

**Comment by jhobz** [comment]
I tried a few different times, some of which I didn't wait and others I waited as much as 30 minutes (especially on the first run). Same result each time.

**Comment by BatedUrGonnaDie** [comment]
Try removing the volume line from `docker-compose.yml` and rebuild the containers.

**Comment by jhobz** [comment]
Well, I get further now at least! It appears to have cached my version of `application.sass` with the syntax error or something, because even if I checkout master I get a SASS syntax error for a line that doesn't exist. Even if I checkout the branch I did make the syntax error on and fix it, it still throws the error.

**Comment by BatedUrGonnaDie** [comment]
Without the volume line you have to rebuild the container on every change.  Docker-toolbox has an error with volumes when it's outside of your user directory I think.

**Comment by jhobz** [comment]
That seems like an unrelated issue, I think. I was on `master` when I built the first time. I tried again but even after rebuilding I still get the SASS error for a line that doesn't exist. Note, the error only happens after I try to access `localhost:3000` in the browser, so I'm fairly certain it has access to all the files it needs.
Here's the specific output of both the build and run commands:
```bash
✔ ~/projects/splits-io master
$ docker build .
Sending build context to Docker daemon  17.31MB
Step 1/19 : FROM ruby:2.3.4
 ---> 4d9cdd30c445
Step 2/19 : RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
 ---> Using cache
 ---> 76985f5a47f8
Step 3/19 : RUN mkdir /app
 ---> Using cache
 ---> a907fe9192c2
Step 4/19 : WORKDIR /app
 ---> Using cache
 ---> 522a948f75c9
Step 5/19 : ADD Gemfile /app/Gemfile
 ---> Using cache
 ---> 84416d011ef0
Step 6/19 : ADD Gemfile.lock /app/Gemfile.lock
 ---> Using cache
 ---> f70bb1021f5f
Step 7/19 : RUN bundle install
 ---> Using cache
 ---> a2eaec175043
Step 8/19 : ENV TWITCH_CLIENT_ID put_your_client_id_here
 ---> Using cache
 ---> d3696024a16e
Step 9/19 : ENV TWITCH_CLIENT_SECRET put_your_client_secret_hete
 ---> Using cache
 ---> 9c044377108f
Step 10/19 : ENV READ_ONLY_MODE 0
 ---> Using cache
 ---> 7250fdc61da3
Step 11/19 : ENV ENABLE_ADS 0
 ---> Using cache
 ---> cbbbc792fe84
Step 12/19 : ENV RAILS_ENV development
 ---> Using cache
 ---> d87d4347dd20
Step 13/19 : ENV DATABASE_URL postgres://postgres@db/postgres
 ---> Using cache
 ---> d43b79baa92f
Step 14/19 : ENV S3_BUCKET splits-io
 ---> Using cache
 ---> 2b802637f719
Step 15/19 : ENV AWS_REGION local
 ---> Using cache
 ---> 3e37e1074f8c
Step 16/19 : ENV AWS_ACCESS_KEY_ID beep
 ---> Using cache
 ---> 7fe390a3c7ba
Step 17/19 : ENV AWS_SECRET_KEY boop
 ---> Using cache
 ---> 1bd21678d4e9
Step 18/19 : ADD . /app
 ---> 769aaca9353d
Step 19/19 : EXPOSE 3000
 ---> Running in 8ed5cb9b234f
 ---> 05ba671b865f
Removing intermediate container 8ed5cb9b234f
Successfully built 05ba671b865f
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
✔ ~/projects/splits-io master
$ docker-compose up
Starting splitsio_s3_1 ...
Starting splitsio_db_1 ...
Starting splitsio_s3_1
Starting splitsio_s3_1 ... done
Starting splitsio_web_1 ...
Starting splitsio_web_1 ... done
Attaching to splitsio_db_1, splitsio_s3_1, splitsio_web_1
db_1   | 2017-10-21 00:27:51.380 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1   | 2017-10-21 00:27:51.380 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1   | 2017-10-21 00:27:51.381 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1   | 2017-10-21 00:27:51.400 UTC [19] LOG:  database system was shut down at 2017-10-20 17:19:13 UTC
web_1  | I, [2017-10-21T00:28:00.615755 #9]  INFO -- : Writing /app/public/assets/application-84e38cbef8748e132c0bb9927bd34961fdd418e4db79a3e0422d54615624ef48.js.gz
web_1  | rails aborted!
web_1  | Sass::SyntaxError: Invalid CSS after "...-width: 768px) ": expected media query list, was "{"
web_1  | /app/app/assets/stylesheets/application.sass:117
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/scss/parser.rb:1278:in `expected'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/scss/parser.rb:1208:in `expected'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/scss/parser.rb:74:in `parse_media_query_list'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:921:in `parse_media_directive'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:838:in `parse_directive'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:655:in `parse_line'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:540:in `build_tree'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:559:in `block in append_children'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:558:in `each'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:558:in `append_children'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:417:in `_to_tree'
web_1  | /usr/local/bundle/gems/sass-3.5.1/lib/sass/engine.rb:290:in `render'
web_1  | /usr/local/bundle/gems/sass-rails-5.0.6/lib/sass/rails/template.rb:47:in `evaluate'
web_1  | /usr/local/bundle/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
web_1  | /usr/local/bundle/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
web_1  | /usr/local/bundle/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
web_1  | /usr/local/bundle/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
web_1  | /usr/local/bundle/gems/railties-5.0.5/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
web_1  | /usr/local/bundle/gems/railties-5.0.5/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
web_1  | /usr/local/bundle/gems/railties-5.0.5/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
web_1  | /usr/local/bundle/gems/railties-5.0.5/lib/rails/commands.rb:18:in `<top (required)>'
web_1  | bin/rails:4:in `require'
web_1  | bin/rails:4:in `<main>'
web_1  | Tasks: TOP => assets:precompile
web_1  | (See full trace by running task with --trace)
web_1  | zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
web_1  | zlib(finalizer): the stream was freed prematurely.
splitsio_web_1 exited with code 1
```

Note that the SASS error mentions line 117 in `application.sass`, but that line doesn't exist. The file ends at L115.

**Comment by BatedUrGonnaDie** [comment]
Try using `docker-compose build` and see what happens.  Not sure if there is any difference between the 2 but it might help.

**Comment by jhobz** [comment]
Well that stopped the SASS error from showing up, but I'm still greeted with "The site can't be reached."

**Comment by BatedUrGonnaDie** [comment]
If you have Kinematic installed can you start the container, and then find it in Kinematic and find the dedicated ip that it's bound to, and connect directly to that?

Post 4 here talks about it: https://forums.docker.com/t/solved-cant-access-rails-app-containers-port/6092/4

**Comment by jhobz** [comment]
That worked! Weird that it tied to 192.168.99.100 and I can't seem to change it... but at least now I can access it! Thanks for the assistance.

**Comment by BatedUrGonnaDie** [comment]
Docker-toolbox has some really weird quirks to it for some reason.  Hopefully in the future regular win10 will support the full docker install.

**Comment by BatedUrGonnaDie** [comment]
Apparently full docker will also work on Windows 10 education version as well if you have access to that by some means.
