### ISSUE TITLE
Trying to start local server fails with "Could not find 'bundler' (1.17.3)"

### ISSUE THREAD

**Issue by Blackop778** [glacials/splits-io#658]
More context for the error message:
```
sudo -E docker-compose run --rm web bash -c 'bundle install --jobs $((`nproc` - 1)) && yarn install && rails db:migrate && skylight disable_dev_warning'
Starting splits-io_redis_1 ... done
Starting splits-io_s3_1    ... done
Traceback (most recent call last):
	2: from /app/bin/bundle:3:in `<main>'
	1: from /usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:252:in `bin_path'
/usr/local/lib/ruby/site_ruby/2.6.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /app/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
Makefile:21: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by BatedUrGonnaDie** [comment]
What platform, docker version, and docker-compose version are you running?

**Comment by Blackop778** [comment]
`Ubuntu 18.04.3 LTS`
`Docker version 19.03.5, build 633a0ea838`
`docker-compose version 1.25.0, build 0a186604`

**Comment by BatedUrGonnaDie** [comment]
I'll try and look into this tomorrow.

**Comment by BatedUrGonnaDie** [comment]
@glacials made a lot of changes and most likely fixed this problem over the last 2 days.  Can you recheck and see if this is still an issue?

**Comment by Blackop778** [comment]
This seems to have been fixed, thanks :)
